### ISSUE TITLE
입력시 따음표(`'`, `"`)에 대한 처리

### ISSUE THREAD

**Issue by cos18** [cos18/minishell#2]
입력으로 들어왔을 때 큰 따음표(`"`)나 작은 따음표(`'`)가 들어왔을 때 여러가지 처리를 해야합니다.
- [x] 따음표가 열렸을 때, 앤터가 쳐지면 새로운 줄을 받아야 합니다
- [x] 종류가 다른 따음표는 문자로 처리해야 합니다.

### 예시
```shell
minishell$ echo 'hello"
> "world''
> aaa'test
> '
END
```

### 마감기한

2021-01-04 18시 온라인 미팅 전까지

**Comment by davkim1030** [comment]
commit #0a0ff3a9cd052060cbac13e62c4baaa038d97bd8에서 처리했습니다.
확인 부탁드립니다!

**Comment by cos18** [comment]
```C
typedef struct	s_bash
{
	char		*cmd;
	char		**token;
}				t_bash;
```
이런식으로 t_bash 구조체를 수정해주시고 리펙토링 부탁드립니다!
